blog/urls.py
from django.urls import path 
from .views import BlogListView, BlogCreateView, BlogDetailView
app_name="blog"

urlpatterns = [
    path('', BlogListView.as_view(), name="home"), 
    path('create/', BlogCreateView.as_view(), name="create"),
    path('<int:pk>/', BlogDetailView.as_view(), name="detail")
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import HomeView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', HomeView.as_view(), name='home'),
    path('blog/'  ,include('blog.urls', namespace='blog'))

]

blog/forms.py
from django import forms
from .models import Post


class PostCreateForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'content')

core/views.py
from django.shortcuts import render
from django.views.generic import View


class HomeView(View):
    def get(self, request, *args, **kwargs):
        context={

        }
        return render(request, 'index.html', context)

templates/blog_create.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form method="POST">
{% csrf_token %}
title{{form.title}}
<br>
content{{form.content}}
<button type="submit">Submit</button>
</form>
</body>
</html>

templates/blog_detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog Detail</title>
</head>
<body>
{{post.title}}
<br>
{{post.excerpt}}
<br>
{{post.content}}
</body>
</html>

templates/blog_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Blog list</title>
</head>
<body>
<h1>Blog List</h1>
<br>
{%for post in posts%}
<a href="{% url 'blog:detail' post.id %}">{{post.title}}</a>
{%endfor%}
<br>
<a href="{% url 'blog:create' %}">Create</a>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
hola, visita mi <a href="{%url 'blog:home' %}">blog aqui</a>
</body>
</html>